FROM node:16-slim AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
COPY ./src ./src
RUN npm ci --production && npm cache clean --force

FROM build as prod
COPY --from=build /usr/src/app /usr/src/app
EXPOSE 3000
CMD ["node","src/index.js"]