FROM node:16

RUN user add -m nodeapp

USER nodeappuser

RUN whoami

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "node", "src/index.js" ]

# Now, since we are aware of the fact that having the default user means root in order to avoid this we can specify the default user besides root